include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/Manage.cmake")
set(SDL_VERSION "3.2.16")
set(SDL_SHADERCROSS_VERSION "392d12a")
set(STB_VERSION "f58f558")

CPMAddPackage(
  URI
  "gh:libsdl-org/SDL#release-${SDL_VERSION}"
  NAME "sdl"
  OPTIONS "SDL_INSTALL OFF" "SDL_UNINSTALL OFF" "SDL_INSTALL_TESTS OFF" "SDL_TESTS OFF"
)
list(APPEND SYSTEM_INCLUDE_DIRECTORIES "${sdl_SOURCE_DIR}/include")
list(APPEND LIBRARIES "SDL3-static")

install(TARGETS "SDL3-static" "SDL3_Headers" EXPORT "LLVMExports")
CPMAddPackage(
  URI
  "gh:libsdl-org/SDL_shadercross#${SDL_SHADERCROSS_VERSION}"
  NAME "sdl_shadercross"
  OPTIONS
    "SDLSHADERCROSS_VENDORED ON"
    "SDLSHADERCROSS_SHARED OFF"
    "SDLSHADERCROSS_SPIRVCROSS_SHARED OFF"
    "SDLSHADERCROSS_STATIC ON"
    "SDLSHADERCROSS_CLI OFF"
)
list(APPEND SYSTEM_INCLUDE_DIRECTORIES "${sdl_shadercross_SOURCE_DIR}/include")
list(APPEND LIBRARIES "SDL3_shadercross-static")
set(
  DXCOMPILER_DLL_SOURCE
  "${sdl_shadercross_BINARY_DIR}/external/DirectXShaderCompiler/${CMAKE_BUILD_TYPE}/bin/dxcompiler.dll"
)
set(DXCOMPILER_DLL_DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_BUILD_TYPE}/dxcompiler.dll")
add_custom_target(
  "copy_dxcompiler"
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${DXCOMPILER_DLL_SOURCE}" "${DXCOMPILER_DLL_DESTINATION}"
  DEPENDS "SDL3_shadercross-static"
)
list(APPEND DEPENDENCIES "copy_dxcompiler")

CPMAddPackage(URI "gh:nothings/stb#${STB_VERSION}" NAME "stb")
list(APPEND SYSTEM_INCLUDE_DIRECTORIES "${stb_SOURCE_DIR}")
list(APPEND COMPILER_DEFINITIONS "STB_IMAGE_IMPLEMENTATION")
