if("${CMAKE_SOURCE_DIR}" STREQUAL "${CMAKE_CURRENT_SOURCE_DIR}")
  set(IS_SUBDIRECTORY OFF)
else()
  set(IS_SUBDIRECTORY ON)
endif()

set(CMAKE_VS_DEBUGGER_WORKING_DIRECTORY "$(ProjectDir)\\.." CACHE PATH "")
set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" PROPERTY VS_STARTUP_PROJECT "${NAME}")

set(CMAKE_TLS_VERIFY OFF CACHE BOOL "")
