#pragma once

#include <filesystem>
#include <string>
#include <vector>

std::string unsigned_char_to_hex(unsigned char character);

inline std::vector<std::string> args = {};
inline std::vector<std::filesystem::path> resources = {};

inline const std::string usage =
  "Usage: CSResource (<resource1> <resource2> ... <resourceN>) <output_shader_directory> "
  "<output_include_directory> <output_source_directory>]";
inline std::string include_content = "// This file is automatically generated, do not edit manually.\n\n"
                                     "#pragma once\n\n"
                                     "#include <vector>\n\n"
                                     "namespace cse::resource\n"
                                     "{\n"
                                     "  struct compiled_shader\n"
                                     "  {\n"
                                     "    const std::vector<unsigned char> dxil;\n"
                                     "    const std::vector<unsigned char> spirv;\n"
                                     "  };\n\n";
inline std::string source_content = "// This file is automatically generated, do not edit manually.\n\n"
                                    "#include \"resource.hpp\"\n\n"
                                    "namespace cse::resource\n"
                                    "{\n";
